### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dchaplinsky** [The-Penultimate-Defenestrator/wikipedia-map#23]
Hello.

I want to reuse parts of your projects in our open source project https://github.com/dchaplinsky/pep.org.ua.

Do you have any license restrictions/objections?

**Comment by controversial** [comment]
The license is MIT. You're welcome to re-use the code, as long as you have
a notice that I am the original author. A notice of copyright in the code
will suffice, but beyond providing attribution there are no restrictions to
your use of the code.

Thanks!

**Comment by dchaplinsky** [comment]
![mkovb](https://cloud.githubusercontent.com/assets/131186/17422072/5ab6b54e-5ab7-11e6-92db-090c3aa129cd.jpg)
