### ISSUE TITLE
executing `api/api.py`

### ISSUE THREAD

**Issue by Yissam** [The-Penultimate-Defenestrator/wikipedia-map#24]
Hi,
i have the error below when i try to execute  >python api.py to run the flask server.

> Traceback (most recent call last):
>   File "api.py", line 10, in <module>
>     from wikipedia_parse import *
>   File "C:\WikiMap\wikipedia-map-master\api\wikipedia_parse.py", line 164
>     print is_article(":Cows"), is_article("WP:UA")  # Test if it's an article
>                    ^
> SyntaxError: invalid syntax

Thank you in advance for your help

**Comment by controversial** [comment]
Sorry, Wikipedia Map is currently written for Python 2 and unfortunately
does not support Python 3. I'm going to configure a new server for Python 3
Flask, and the script will probably be updated in the next few months.

In the meantime, please execute with Python 2 and let me know if you have
further issues

Thanks,
Luke

**Comment by Yissam** [comment]
Thank you for your reactivity.

i have just executed it with Python 2.7.11 and i have the error below.

> Traceback (most recent call last):
>   File "api.py", line 10, in <module>
>     from wikipedia_parse import *
>   File "C:\WikiMap\wikipedia-map-master\api\wikipedia_parse.py", line 10, in <module>
>     import bs4
> ImportError: No module named bs4

**Comment by controversial** [comment]
You'll need to install the BeautifulSoup module.

**Comment by Yissam** [comment]
Flask server was started on http://127.0.0.1:12345.
 when i try to reach this address by the browser i have **error 404 not Found** 

> - Restarting with stat
> - Debugger is active!
> - Debugger pin code: 180-514-756
> - Running on http://127.0.0.1:12345/ (Press CTRL+C to quit)
>   127.0.0.1 - - [25/Aug/2016 17:07:26] "GET / HTTP/1.1" 404 -

**Comment by controversial** [comment]
Yes, the API provides endpoints at sub-URLs but nothing at `/`. Try `localhost:12345/links?page=cats` to see the connections Wikipedia Map would make for that page.

**Comment by Yissam** [comment]
> ConnectionError: HTTPSConnectionPool(host='en.wikipedia.org', port=443): Max retries exceeded with url: /w/api.php?redirects=1&format=json§ion=0&prop=text&action=parse&page=cats (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000047D4A90>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

**Comment by Yissam** [comment]
I have this connection error towards en.wikipedia.org!!

**Comment by Yissam** [comment]
![image](https://cloud.githubusercontent.com/assets/21241906/17975476/229257c0-6aea-11e6-860b-67fbaeb25e55.png)

**Comment by controversial** [comment]
Can you successfully visit this page in your browser?

**Comment by Yissam** [comment]
yes ...

![image](https://cloud.githubusercontent.com/assets/21241906/17976085/3a9187d6-6aec-11e6-86b4-1bdfd24db544.png)

**Comment by Yissam** [comment]
It's corrected. it was a proxy problem

**Comment by controversial** [comment]
I'm glad. If you have any more questions, you're welcome to open new issues. Thanks 😀

**Comment by Yissam** [comment]
thank you very much

**Comment by controversial** [comment]
No problem 😉
