### ISSUE TITLE
Failed to load resource: net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by Yissam** [The-Penultimate-Defenestrator/wikipedia-map#25]
Hi,
When i test with the following url http://localhost:12345/links?page=cats , i have the ansewer below.

> ["Homo sapiens", "Carnivore", "Fur", "Feral cat", "Felidae", "Pet", "Vermin", "Latin language", "Felinae", "Mammal"]

but when i try to start index.html  i have  an error in the console of my browser 

![image](https://cloud.githubusercontent.com/assets/21241906/17977044/61335ad2-6af0-11e6-9cbf-be78a08a0677.png)

thank you in advance

**Comment by controversial** [comment]
What does the page look like after you get this error?

**Comment by controversial** [comment]
Sorry, that's actually supposed to be there, and that shouldn't affect the functionality of the page. It's intentional; I don't want local testing to count on Google Analytics. You don't need to worry about it 😉

**Comment by Yissam** [comment]
I have solved this issue as follows: removed from chrome extension and i disable the developer mode.

**Comment by controversial** [comment]
That's not a solution, disabling developer mode just hides the error, but it's still there. Anyway, please don't worry about it, Wikipedia Map works correctly even with this error.

**Comment by Yissam** [comment]
Thank you, it is noted.

**Comment by Yissam** [comment]
![image](https://cloud.githubusercontent.com/assets/21241906/17977683/fa09f606-6af2-11e6-8341-578595d2fe93.png)

**Comment by Yissam** [comment]
i have this error  when I click go

**Comment by controversial** [comment]
The [CORS chrome extension](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en) may be necessary for developing in Chrome.

**Comment by controversial** [comment]
Are you trying to contribute to Wikipedia Map or just to use it? If you just want to try it, it's working at http://luke.deentaylor.com/wikipedia/
