### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by gg4u** [The-Penultimate-Defenestrator/wikipedia-map#31]
Hi Luke, may want to check:

XMLHttpRequest cannot load https://wikipedia-map.now.sh/pagename?page=dna. Redirect from 'https://wikipedia-map.now.sh/pagename?page=dna' to 'https://zeit.co/controversial/api/eokchmmhgl?redirect=1' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://luke.deentaylor.com' is therefore not allowed access.

**Comment by controversial** [comment]
I'll take a look later

**Comment by controversial** [comment]
Looks like the deployment just failed for whatever reason. It's all fixed now. Thanks so much for reporting — I probably wouldn't have noticed this for a while otherwise.
