### ISSUE TITLE
Feature: Add next terms

### ISSUE THREAD

**Issue by zub0r** [The-Penultimate-Defenestrator/wikipedia-map#34]
It would be great if it was possible to add a term after initial search without losing connections - e.g. for brainstorming purposes.

Great tool, btw - really appreciate

**Comment by controversial** [comment]
This shouldn't be too hard to add, I don't think, I'll look into it when I get a chance. Thanks for the kind words :)

**Comment by controversial** [comment]
This is implemented! Now, when you click “Go,” it won’t reset the network; it will just update the start nodes to match what's in the input. There's a new “clear” button for resetting the canvas.
