### ISSUE TITLE
Data Source for the Map

### ISSUE THREAD

**Issue by arumugaguru** [The-Penultimate-Defenestrator/wikipedia-map#36]
Hi,

Can you please let me know the data source which you are using in the Flask Server API?

Thanks,

**Comment by controversial** [comment]
I'm using the official Wikipedia API hosted at `https://en.wikipedia.org/w/api.php` to retrieve the HTML of each wikipedia article, and the logic for extracting connections is my own algorithm, accessible [here](https://github.com/controversial/wikipedia-map/blob/master/api/wikipedia_parse.js) in this repo. The documentation for the API is [here](https://www.mediawiki.org/wiki/API:Main_page).
