### ISSUE TITLE
Start flask server

### ISSUE THREAD

**Issue by zigmok** [The-Penultimate-Defenestrator/wikipedia-map#38]
Hi, I am running flask on python2.7.  Is the code for the localserver gone? I cant find the api/api.py anymore :( 

Regards

**Comment by olisteadman** [comment]
It looks like api/api.py was deleted in commit 136cf722b84d66f1f1836c9e334b6fab28886d3f as part of converting the project from Flask to more Node-oriented. @controversial would you be able to update the README to reflect this? Can we do anything to help?

**Comment by controversial** [comment]
Thanks for the heads up! I updated the README with a new set of instructions.
