### ISSUE TITLE
Unicode problem: "Zürich"

### ISSUE THREAD

**Issue by cclauss** [The-Penultimate-Defenestrator/wikipedia-map#4]
https://en.wikipedia.org/wiki/Z%C3%BCrich

**Comment by controversial** [comment]
If I put in Zürich like that, I get a `null` bubble. I'll check it out.

**Comment by controversial** [comment]
Ok, the script calls http://luke.deentaylor.com/wikipedia/api/pagename?page=Z%FCrich. If I put "Z%FCrich" just like that into the `wikipedia_parse.py` script, I get actual pages back. Looks like the problem is in calling the flask server, somehow.

**Comment by cclauss** [comment]
Start with `Switzerland` then try clicking on `Zürich`.  You can't open a Unicode name by clicking on it.

You might to adding this at the top of your imports in both .py files:

`from __future__ import unicode_literals`

**Comment by controversial** [comment]
@cclauss, I'll try that code. Right now, I'm just converting things to unicode wherever I can ;-)

**Comment by The-Penultimate-Defenestrator** [comment]
@cclauss Now I'm somehow passing "https://en.wikipedia.org/wiki/Z%EF%BF%BDrich", which unquotes to "https://en.wikipedia.org/wiki/Z\xef\xbf\xbdrich"

**Comment by controversial** [comment]
OK, @cclauss. Could you check out the new `unicode` branch? It reflects the changes I've made. Running wikipedia_parse.py works great, but if I do it through flask I have issues for some reason. The tests at the bottom of the file try passing "Zürich" both with the character, and with the percent code.

**Comment by controversial** [comment]
OK, here we go. You can now open "Zürich" without any issue. The only remaining thing to do is figure out why it's displaying as "ZÃ¼rich"

**Comment by controversial** [comment]
Now I've got it displaying as "Z%C3%BCrich" which is a lot closer. Almost there...

**Comment by controversial** [comment]
I've got it working now 😃:
![](http://i.imgur.com/AXlzCA2.png)

**Comment by cclauss** [comment]
Maybe you should move to Python 3...  This issue still exists. Trying to fix Unicode bugs in Python 2 is like playin whack-a-mole.

**Comment by controversial** [comment]
Flask doesn't support Python 3, unfortunately 😥. Otherwise I would.

**Comment by controversial** [comment]
I'm able to expand Switzerland with Zürich. What are you still unable to do?

**Comment by cclauss** [comment]
http://flask.pocoo.org/docs/0.10/python3/ seems to support Python3.  Flask is bundled in Pythonista3 too.

I am trying to enter `Zürich` and more importantly `Val Müstair` as a search term.

**Comment by controversial** [comment]
You're right, if I enter "Zurich" even without the umlaut, I can see this but not expand it. I'll look into this.

**Comment by controversial** [comment]
So my strategy for dealing with Python 2 unicode, I think, is to _not deal with it at all_. What I mean by this is, everything that goes into and out of the API will be URL encoded. The python script will never see "Zürich," it will only see "Z%C3%BCrich." It can feed this into http://en.wikipedia.org/wiki/Z%C3%BCrich, etc.

**Comment by controversial** [comment]
And I've fixed it! You can now enter "Zürich" with or without an umlaut, as well as Val Müstair. It's live on my website, and pushed to GitHub.
