### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ElModdy** [The-Penultimate-Defenestrator/wikipedia-map#40]
Hi, I'd like to see your page in action but unfortunately it doesn't seem to work.
I type an article then press go but it remains in the "tour" section.

**Comment by olisteadman** [comment]
@ElModdy I also had no luck trying to run this... although it looks like some code was updated around 5 months ago, I'm not sure how actively the repo is monitored. I can recommend this alternative whilst you wait for news of how to address the issue.

http://factforge.net/graphs-visualizations

It's able to map Wikipedia and other sources in a way that you may find useful.

**Comment by controversial** [comment]
Looking into this now!

**Comment by controversial** [comment]
Should be fixed now. Thanks for reporting! Please reopen if you're having any issues
