### ISSUE TITLE
A bit more helpful text

### ISSUE THREAD

**Issue by cclauss** [The-Penultimate-Defenestrator/wikipedia-map#7]
![a bit more helpful text](https://cloud.githubusercontent.com/assets/3709715/12983198/7f6aed96-d0e8-11e5-9846-36b9efc603df.png)

**Comment by controversial** [comment]
A problem is that on mobile browsers, there is very little room ![](http://i.imgur.com/A0o8tRB.jpg)

Are you suggesting that I put in a label like you have annotated, in the top bar?

**Comment by cclauss** [comment]
I was suggesting that but now I see the problem.  On mobile, it just won't fit.

**Comment by controversial** [comment]
Maybe a tooltip would work better for hover?

**Comment by controversial** [comment]
Closed with latest commit, in which I added hover tooltips to the menu bar items. Reopen if you feel this is inadequate.

**Comment by controversial** [comment]
OK, I've added some text to the background before starting. I'm also planning to implement a much more helpful help dialog, including information about controls, etc. It will probably still include the README as well.

**Comment by cclauss** [comment]
It is looking awesome...  What do you use for the backend?  AWS, Heroku, Google, Bluemix, etc.?

**Comment by controversial** [comment]
It's on my personal web server, which I bought from DigitalOcean. I've
modified the Apache conf files to serve a flask app from the /wikipedia/api
directory.

**Comment by controversial** [comment]
I've got a full interactive help dialog in place. It's modeled after a `UINavigationController`, and I think it works pretty well. Right now, it contains information about controls, about the project in general, and the GitHub README.
